workflows:
  version: 2
  resource_class_jobs:
    jobs:
      - small
      - medium:
          requires:
            - small
      - medium-plus:
          requires:
            - medium
      - broken_build

  # scheduled:
  #   triggers:
  #     - schedule:
  #         cron: "30 * * * *" # use cron syntax to set the schedule
  #         filters:
  #           branches:
  #             only:
  #               - test_branch
  #   jobs:
  #     - broken_build

resource_job_defaults: &resource_job_defaults
  docker: [{image: 'circleci/ruby:2.4.1'}]
  steps: [{run: 'echo $CIRCLE_JOB'}]

jobs:
  # resource class jobs
  small: # 1 vCPU, 2GB RAM
    <<: *resource_job_defaults
    resource_class: small

  medium: # 2 vCPUs, 4GB RAM
    <<: *resource_job_defaults
    resource_class: medium

  medium-plus: # 3 vCPUs, 6GB RAM
    <<: *resource_job_defaults
    resource_class: medium+

  broken_build:
    docker: 
      - image: circleci/ruby:2.4.1
    steps:
      - restore_cache:
          keys:
            - gem-v1-{{ .Branch }}-{{ .Revision }}--{{ checksum "Gemfile" }}
      
      - checkout
      - run: bash test.sh
      - run: bundle install
      
      - save_cache:
          key: gem-v1-{{ .Branch }}-{{ .Revision }}--{{ checksum "Gemfile" }}
          paths:
            - /usr/local/lib/ruby/gems/